#!/bin/tcsh -f

# set environment for including the common Libraries
set WORK_ROOT   = "/home/ic/github/Charles-DesignWare"
set TB_NAME     = "$WORK_ROOT/verification/th/divider_tb.v"
set RTL_FLIST   = "$WORK_ROOT/hdl/sanity.f"

# tcshell script for running behavior simulation using vcs
if ($* == "vcs") then
    # This command runs the simulation and output the simv file for debugging or dumping the wave
    # -y: Specify the library.
    # +libext: Used together with -y to specify the file extension that will be regarded as library files.
    # -f: Specify the filelist containing your design files
    vcs -full64 \
    -f $RTL_FLIST \
    -y $WORK_ROOT/common \
    +libext+.v \
    +libext+.vh \
    +v2k \
    -vcs+lic+wait \
    -l vcs.log \
    -debug_access+all \
    -fsdb \
    -timescale=1ns/1ps \
    $TB_NAME
else if ($* == "simv") then
    # This command runs the simulation until the $finish is reached and dump the wave into the .fsdb file.
    ./simv \
    +vcs+lic+wait \
    -l simv.log \
    +fsdb+autoflush
else if ($* == "verdi") then
    # This command loads the design (.v, for viewing the circuit block) and the waveform (.fsdb) into the Verdi.
    # The parameters are the same as vcs command
    verdi -sv \
    -f $RTL_FLIST \
    -y $WORK_ROOT/common \
    +libext+.v \
    +libext+.vh \
    +v2k \
    -vcs+lic+wait \
    -ssf dut.fsdb \
    -nologo \
    $TB_NAME
else
    echo "error: please specify either 'vcs', 'simv' or 'verdi' as the input"
endif
